### PR TITLE
Filter sensitive params

### PR DESCRIPTION
**Pull request by zph**
This PR adds functionality to *recursively* redact sensitive keys for logger information.

By default, it will redact things like:

```
["password", "token", "authorization", "api_token", "_csrf_token"]
```
I added a couple tests to verify the behavior, updated README and moduledoc.

### CODE REVIEW

**Comment by zph** [comment]
@Ebtoulson :D another PR for you! Thank you and happy to have feedback/alterations/suggestions on the implementation. It seems to be doing the right things in testing and in my use case.

**Comment by Ebtoulson** [comment]
Hey Zander, Sorry for the slow response.

I've just got a few questions / concerns:

`drop_lines_matching` - It seems like the example, you provided, really just drop lines for certain routes / controllers / plugs. Is that the intended purpose? If so then I'd recommend removing the plug logger from the endpoint and only including it where you want it. If you are using phx routing, creating a `pipeline :log` that includes the plug works pretty well.

`filtered_keys` - ok so this is similar to phx's `filter_parameters`. My only concern with this is because it's doing a deep filter, it could affect performance for nested maps whereas `filter_parameters` only checks parameters (no recursion). I like the idea, I just don't know if I'd want that by default. 

I've been tossing around the idea of providing a transformation pipeline for logs, then filtering and even log shapes could be customized..I just haven't really dedicated enough time to look into it.
Thoughts?

**Comment by zph** [comment]
👋

1. Yes! Totally the intention and desire. I have a use case of needing to include logger generally vs setting up separate pipelines and the possibility of it being left out.

The use case: Healthcheck endpoints flood the log collector with nonsense.

2. I believe it's opt in by default in competing library and having that data flow into logs shouldn't be possible by default. The deep filter isn't showing performance problems in my own testing, possibly because the data structures are only 2 levels deep.

We could take a similar approach to https://github.com/bleacherreport/plug_logger_json#configure-plug_logger_json, which is to recommend the common things to filter out but it's up to whoever configures to use that setup and `opt-in`. How does that sound?

PS - This is in production from my fork and doing what's advertised on the tin.

**Comment by zph** [comment]
Also... HI!

**Comment by Ebtoulson** [comment]
Yea I like that approach better, then we could skip the check all together if no keys were supplied.
Let me know if you want some help on these changes.

ps. it looks like theres a lot of style issues so please run `credo` or `./script/test`.
I need to set up a CI service thats visible to the public

**Comment by zph** [comment]
Updated to fix credo warnings :).

I'll look at skipping processing entirely if the config settings are nil.

**Comment by Stratus3D** [comment]
Hi @zph !

Sorry for the late reply here. I've discussed this PR briefly with @Ebtoulson and I think the best approach here is to close this PR. Let me explain.

There are two features implemented in this PR:

* **`drop_lines_matching` - if the log line encoded as a string matches one or more parameters drop the log line.** This feature was added so that requests to certain routes could be dropped from the logs. The approach we use for this is to only call `plug ExJsonLogger.Plug.Logger` for routes you want logged. @Ebtoulson covered this in an earlier comment:

  > drop_lines_matching - It seems like the example you provided really just drop lines for certain routes / controllers / plugs. Is that the intended purpose? If so then I'd recommend removing the plug logger from the endpoint and only including it where you want it. If you are using phx routing, creating a pipeline :log that includes the plug works pretty well.

* **`filtered_keys` - recursively find and replace values for keys in the filtered keys list with a placeholder `[REDACTED]` value.** Our concern about this is that it will give a false sense security. Devs may rely on the redaction logic to exclude all sensitive values rather than explicitly logging the only values they know are safe. (Explicitly including metadata you know to be safe is safer than explicitly excluding/filtering metadata you know to be sensitive as a mistake doesn't result in a leak). The log you have will work for parsed query and body params, but it will not work for things like raw query string (the `query_string` metadata). It's best to only log metadata if you are certain it doesn't contain secrets, or rely on Phoenix's built in basic parameter filter - https://hexdocs.pm/phoenix/Phoenix.Logger.html#module-parameter-filtering

Thank you for your contribution @zph ! Please open an issue if you find a bug or have another feature you'd like to add.

**Pull request closed without merging**
